### ISSUE TITLE
Sprint Backlog 4

### ISSUE THREAD

**Issue by ayantariq** [seanradel2020/MaineFrame#52]
The comments from Deliverable 3 must be addressed. 
For any comment that were not addressed, deduct -2 points. 
Should reflect the product backlog. That is, all the user stories that are assigned to Sprint 4 in the product backlog, should be shown in the Sprint Backlog 4.
For any missing user story, deduct -2 points.
If the Sprint Backlog 4 does not reflect the product backlog, deduct -5 points.

**Comment by noahbrooks** [comment]
Need review from @ayantariq or @Dydomio before submitting
