### ISSUE TITLE
SRS + Use Case Models and Descriptions + Architecture design

### ISSUE THREAD

**Issue by ayantariq** [seanradel2020/MaineFrame#54]
Need to check if the comments from Deliverable 3 have been addressed. 
For any comment that is not addressed (every single one), deduct -1 points. 
If the SRS, the UCM and AD didn’t need any update, then the 5% will be added to sequence diagram grade and no grade will be given for SRS+UCM+AD. That is, SRS+UCM+AD will be 0 and Sequence Diagram will be /15. 
**No change needed**

**Comment by Dydomio** [comment]
No changes needed.
