### ISSUE TITLE
Sequence Diagram 

### ISSUE THREAD

**Issue by ayantariq** [seanradel2020/MaineFrame#55]
The comments from Deliverable 2 must be addressed. 
For any comment that were not addressed, deduct -2 points. 
If the number of ASD were below 7 or DSD were below 3 in Deliverable 3 and they did not change in Deliverable 4, deduct -5 points for each.

**Comment by noahbrooks** [comment]
Nicole & Noah fixed their sequence diagrams, @ayantariq needs to fix theirs

**Comment by ayantariq** [comment]
Fixed
