### ISSUE TITLE
Domain Model Update

### ISSUE THREAD

**Issue by noahbrooks** [seanradel2020/MaineFrame#63]

**Comment by noahbrooks** [comment]
Should be good to go, could do with a look over @AndresVargas4

**Comment by AndresVargas4** [comment]
I changed createEvent() to getMarker(), as we already have createEvent() under event planner and I wasnt sure if we can have the 
"same" methods over different classes. Let me know what you think @noahbrooks

**Comment by noahbrooks** [comment]
We have the same methods in other classes and were not docked points, however I like the method you replaced it with better @AndresVargas4 closing this issue
